[pytest]
DJANGO_SETTINGS_MODULE = core.settings
python_files = test_*.py *_test.py tests.py
python_classes = Test*
python_functions = test_*
testpaths = tests apps/accounts/tests apps/organizations/tests apps/projects/tests apps/permissions/tests apps/issues/tests apps/sprints/tests apps/workflow/tests apps/label/tests
addopts = --strict-markers -ra

markers =
    django_db: mark test as requiring database access (pytest-django)
