# Generated by Django 5.2.11 on 2026-07-07 09:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_issue_completed_at_storypointhistory'),
        ('sprints', '0003_parallel_sprints'),
        ('workflow', '0004_issuestatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot_type', models.CharField(choices=[('start', 'Start'), ('daily', 'Daily'), ('end', 'End')], default='start', max_length=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='sprints.sprint')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sprint snapshot',
                'verbose_name_plural': 'sprint snapshots',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='SprintIssueCommitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('committed_story_points', models.IntegerField(blank=True, null=True)),
                ('committed_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('committed_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sprint_commitments', to='workflow.workflowstatus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_commitments', to='issues.issue')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='sprints.sprintsnapshot')),
            ],
            options={
                'verbose_name': 'sprint issue commitment',
                'verbose_name_plural': 'sprint issue commitments',
            },
        ),
    ]
