# Generated by Django 6.0.5 on 2026-07-07 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0012_analytics_constraints_indexes'),
        ('sprints', '0004_sprintsnapshot_sprintissuecommitment'),
        ('workflow', '0006_analytics_constraints_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprintsnapshot',
            options={'ordering': ['-created_at'], 'verbose_name': 'sprint snapshot', 'verbose_name_plural': 'sprint snapshots'},
        ),
        migrations.RemoveField(
            model_name='sprintsnapshot',
            name='captured_at',
        ),
        migrations.AddIndex(
            model_name='sprintsnapshot',
            index=models.Index(fields=['sprint', 'snapshot_type'], name='sprints_snap_sprint_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='sprintissuecommitment',
            constraint=models.UniqueConstraint(fields=('snapshot', 'issue'), name='sprints_commitment_unique_snapshot_issue'),
        ),
        migrations.AddConstraint(
            model_name='sprintsnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('snapshot_type__in', ['start', 'end'])), fields=('sprint', 'snapshot_type'), name='sprints_snapshot_unique_start_end'),
        ),
    ]
