import type { Sprint } from '@/types/sprints'

export const mockSprints: Sprint[] = [
  {
    id: 'sprint-42',
    projectId: '1',
    name: 'Sprint 42',
    status: 'active',
    dateRange: 'Jun 2 – Jun 16',
    daysRemaining: 14,
    issueCount: 24,
    completedCount: 11,
    goal: 'Ship onboarding v2 and push notifications',
  },
  {
    id: 'sprint-41',
    projectId: '1',
    name: 'Sprint 41',
    status: 'completed',
    dateRange: 'May 19 – Jun 1',
    issueCount: 18,
    completedCount: 18,
  },
  {
    id: 'sprint-8',
    projectId: '2',
    name: 'Sprint 8',
    status: 'active',
    dateRange: 'Jun 4 – Jun 18',
    daysRemaining: 14,
    issueCount: 12,
    completedCount: 3,
    goal: 'Landing page hero and pricing section',
  },
  {
    id: 'sprint-15',
    projectId: '3',
    name: 'Sprint 15',
    status: 'active',
    dateRange: 'Jun 1 – Jun 15',
    daysRemaining: 11,
    issueCount: 42,
    completedCount: 19,
    goal: 'Migrate payment webhooks to event mesh',
  },
  {
    id: 'sprint-14',
    projectId: '3',
    name: 'Sprint 14',
    status: 'completed',
    dateRange: 'May 18 – May 31',
    issueCount: 38,
    completedCount: 35,
  },
  {
    id: 'sprint-7',
    projectId: '2',
    name: 'Sprint 7',
    status: 'planned',
    dateRange: 'Jun 19 – Jul 3',
    issueCount: 0,
    completedCount: 0,
    goal: 'Blog integration and SEO metadata',
  },
]
