import type { Sprint } from '@/types/sprints'
import { formatDateRange } from '@/utils/sprintDates'

const sprints: Omit<Sprint, 'dateRange'>[] = [
  {
    id: 'sprint-42',
    projectId: '1',
    name: 'Sprint 42',
    status: 'active',
    startDate: '2026-06-01',
    endDate: '2026-06-14',
    daysRemaining: 14,
    issueCount: 14,
    completedCount: 10,
    goal: 'Ship onboarding v2 and push notifications',
    capacityPoints: 40,
    durationWeeks: '2',
  },
  {
    id: 'sprint-43',
    projectId: '1',
    name: 'Sprint 43',
    status: 'planned',
    startDate: '2026-06-15',
    endDate: '2026-06-28',
    issueCount: 1,
    completedCount: 0,
    goal: 'Offline support and performance tuning',
    capacityPoints: 40,
    durationWeeks: '2',
  },
  {
    id: 'sprint-41',
    projectId: '1',
    name: 'Sprint 41',
    status: 'completed',
    startDate: '2026-05-19',
    endDate: '2026-06-01',
    issueCount: 18,
    completedCount: 15,
    goal: 'Authentication hardening',
    durationWeeks: '2',
  },
  {
    id: 'sprint-8',
    projectId: '2',
    name: 'Sprint 8',
    status: 'active',
    startDate: '2026-06-04',
    endDate: '2026-06-18',
    daysRemaining: 14,
    issueCount: 12,
    completedCount: 3,
    goal: 'Landing page hero and pricing section',
    durationWeeks: '2',
  },
  {
    id: 'sprint-15',
    projectId: '3',
    name: 'Sprint 15',
    status: 'active',
    startDate: '2026-06-01',
    endDate: '2026-06-15',
    daysRemaining: 11,
    issueCount: 42,
    completedCount: 19,
    goal: 'Migrate payment webhooks to event mesh',
    capacityPoints: 55,
    durationWeeks: '2',
  },
  {
    id: 'sprint-14',
    projectId: '3',
    name: 'Sprint 14',
    status: 'completed',
    startDate: '2026-05-18',
    endDate: '2026-05-31',
    issueCount: 38,
    completedCount: 35,
    durationWeeks: '2',
  },
  {
    id: 'sprint-7',
    projectId: '2',
    name: 'Sprint 7',
    status: 'planned',
    startDate: '2026-06-19',
    endDate: '2026-07-03',
    issueCount: 0,
    completedCount: 0,
    goal: 'Blog integration and SEO metadata',
    durationWeeks: '2',
  },
]

export const mockSprints: Sprint[] = sprints.map((s) => ({
  ...s,
  dateRange: formatDateRange(s.startDate, s.endDate),
}))
