import type { ProjectIssue } from '@/types/issues'

export const mockIssues: ProjectIssue[] = [
  {
    id: 'i-1',
    projectId: '1',
    sprintId: 'sprint-42',
    key: 'MOB-101',
    title: 'Implement OAuth2 flow for external partners',
    priority: 'high',
    status: 'todo',
    label: 'Frontend',
    assignee: { name: 'Alex', color: '#6366f1' },
    storyPoints: 8,
  },
  {
    id: 'i-2',
    projectId: '1',
    sprintId: 'sprint-42',
    key: 'MOB-104',
    title: 'Update documentation for API v2 endpoints',
    priority: 'low',
    status: 'todo',
    label: 'Docs',
    assignee: { name: 'Sam', color: '#ec4899' },
    storyPoints: 3,
  },
  {
    id: 'i-3',
    projectId: '1',
    sprintId: 'sprint-42',
    key: 'MOB-102',
    title: 'Refactor database schema for user profiles',
    priority: 'medium',
    status: 'in_progress',
    label: 'Backend',
    assignee: { name: 'Jordan', color: '#f59e0b' },
    storyPoints: 5,
    progress: 65,
  },
  {
    id: 'i-4',
    projectId: '1',
    sprintId: 'sprint-42',
    key: 'MOB-098',
    title: 'Fix memory leak in websocket listener',
    priority: 'high',
    status: 'done',
    label: 'Critical',
    assignee: { name: 'Riley', color: '#14b8a6' },
    storyPoints: 5,
    done: true,
  },
  {
    id: 'i-5',
    projectId: '1',
    sprintId: null,
    key: 'MOB-110',
    title: 'Design push notification permission UX',
    priority: 'medium',
    status: 'todo',
    label: 'Design',
    assignee: { name: 'Alex', color: '#6366f1' },
    storyPoints: 5,
  },
  {
    id: 'i-6',
    projectId: '1',
    sprintId: null,
    key: 'MOB-111',
    title: 'Add biometric login fallback',
    priority: 'high',
    status: 'todo',
    label: 'Auth',
    assignee: { name: 'Sam', color: '#ec4899' },
    storyPoints: 8,
  },
  {
    id: 'i-7',
    projectId: '1',
    sprintId: null,
    key: 'MOB-112',
    title: 'Analytics event taxonomy cleanup',
    priority: 'low',
    status: 'todo',
    label: 'Analytics',
    assignee: { name: 'Jordan', color: '#f59e0b' },
    storyPoints: 3,
  },
  {
    id: 'i-8',
    projectId: '1',
    sprintId: 'sprint-43',
    key: 'MOB-120',
    title: 'Offline mode cache strategy',
    priority: 'medium',
    status: 'todo',
    label: 'Mobile',
    assignee: { name: 'Alex', color: '#6366f1' },
    storyPoints: 5,
  },
  {
    id: 'i-9',
    projectId: '3',
    sprintId: 'sprint-15',
    key: 'API-201',
    title: 'Migrate payment webhooks to event mesh',
    priority: 'high',
    status: 'in_progress',
    label: 'Backend',
    assignee: { name: 'Jordan', color: '#f59e0b' },
    storyPoints: 13,
    progress: 40,
  },
  {
    id: 'i-10',
    projectId: '3',
    sprintId: null,
    key: 'API-215',
    title: 'Rate limit configuration UI',
    priority: 'medium',
    status: 'todo',
    label: 'API',
    assignee: { name: 'Riley', color: '#14b8a6' },
    storyPoints: 5,
  },
]
