import type { Project } from '@/types/projects'

export const mockProjects: Project[] = [
  {
    id: '1',
    key: 'MOB',
    name: 'Mobile App',
    description:
      'Redesigning the cross-platform experience for iOS and Android users.',
    status: 'active',
    icon: 'mobile',
    issuesLabel: '12 Open Issues',
    openIssuesLabel: '12 Open Issues',
    progress: 68,
    recentActivity: 'Sarah moved DF-42 to Done',
    members: [
      { name: 'Alex', color: '#6366f1' },
      { name: 'Sam', color: '#ec4899' },
    ],
    extraMembers: 3,
    isMember: true,
    isFavorite: true,
  },
  {
    id: '2',
    key: 'MKT',
    name: 'Marketing Site',
    description: 'New landing pages for the Q3 product launch campaign.',
    status: 'planning',
    icon: 'web',
    issuesLabel: '0 Issues',
    openIssuesLabel: '0 Issues',
    progress: 12,
    recentActivity: 'Planning kickoff scheduled',
    members: [{ name: 'Chris', color: '#94a3b8', initials: 'JS' }],
    isMember: true,
    isFavorite: true,
  },
  {
    id: '3',
    key: 'API',
    name: 'API Service',
    description: 'Migrating legacy monolithic endpoints to a microservice mesh.',
    status: 'at_risk',
    icon: 'api',
    issuesLabel: '42 Critical Issues',
    issuesCritical: true,
    openIssuesLabel: '42 Critical Issues',
    progress: 45,
    recentActivity: 'Jordan flagged webhook timeout',
    members: [
      { name: 'Jordan', color: '#f59e0b' },
      { name: 'Riley', color: '#14b8a6' },
    ],
    isMember: true,
  },
  {
    id: '4',
    key: 'INT',
    name: 'Internal Tools',
    description: 'Legacy admin dashboard — maintenance mode only.',
    status: 'archived',
    icon: 'web',
    issuesLabel: '0 Issues',
    openIssuesLabel: '0 Issues',
    members: [{ name: 'Pat', color: '#94a3b8' }],
    recentActivity: 'Archived after v1 sunset',
  },
]
