# Generated by Django 6.0.5 on 2026-06-22 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("label", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="label",
            new_name="label_label_project_c81674_idx",
            old_name="label_label_project_4a8f2d_idx",
        ),
    ]
