# Generated by Django 6.0.5 on 2026-06-05 12:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0002_add_archived_at"),
        ("sprints", "0001_initial"),
        ("workflow", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("number", models.PositiveIntegerField()),
                ("key", models.CharField(db_index=True, max_length=50, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("lowest", "Lowest"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("highest", "Highest"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("task", "Task"),
                            ("story", "Story"),
                            ("bug", "Bug"),
                            ("subtask", "Subtask"),
                        ],
                        default="task",
                        max_length=20,
                    ),
                ),
                (
                    "story_points",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("labels", models.JSONField(default=list)),
                ("position", models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subtasks",
                        to="issues.issue",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issues",
                        to="projects.project",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reported_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issues",
                        to="sprints.sprint",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issues",
                        to="workflow.workflowstatus",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "issue",
                "verbose_name_plural": "issues",
                "indexes": [
                    models.Index(
                        fields=["project", "status"], name="issues_issu_project_3c2b84_idx"
                    ),
                    models.Index(
                        fields=["project", "sprint"], name="issues_issu_project_bcc24d_idx"
                    ),
                    models.Index(
                        fields=["project", "assignee"], name="issues_issu_project_e632b6_idx"
                    ),
                    models.Index(
                        fields=["project", "position"], name="issues_issu_project_795b03_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "number"), name="issues_issue_project_number_uniq"
                    ),
                ],
            },
        ),
    ]
