# Generated by Django 6.0.5 on 2026-06-16 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0001_initial"),
        ("label", "0001_initial"),
        ("projects", "0003_project_next_issue_number"),
        ("sprints", "0002_sprint_persistence_only"),
        ("workflow", "0003_migrate_legacy_status_categories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="issue",
            name="issues_issue_project_number_uniq",
        ),
        migrations.RemoveIndex(
            model_name="issue",
            name="issues_issu_project_795b03_idx",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="number",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="parent_issue",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="position",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="labels",
        ),
        migrations.RenameField(
            model_name="issue",
            old_name="issue_type",
            new_name="type",
        ),
        migrations.AlterField(
            model_name="issue",
            name="type",
            field=models.CharField(
                choices=[
                    ("task", "Task"),
                    ("bug", "Bug"),
                    ("story", "Story"),
                    ("epic", "Epic"),
                ],
                default="task",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="key",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="issue",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="story_points",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="estimate_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                related_name="issues",
                to="label.label",
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["project", "priority"],
                name="issues_issu_project_934913_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="issue",
            constraint=models.UniqueConstraint(
                fields=("project", "key"),
                name="issues_issue_project_key_uniq",
            ),
        ),
    ]
