# Generated by Django 6.0.5 on 2026-06-22 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0006_issue_parent_subtask"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="issueattachment",
            new_name="issues_issu_issue_i_2d2a93_idx",
            old_name="issues_issu_issue_i_9917eb_idx",
        ),
    ]
