# Generated by Django 5.2.11 on 2026-07-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0010_backfill_analytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueactivity',
            name='event_type',
            field=models.CharField(choices=[('status_changed', 'Status changed'), ('assignee_changed', 'Assignee changed'), ('sprint_changed', 'Sprint changed'), ('comment_added', 'Comment added'), ('comment_deleted', 'Comment deleted'), ('attachment_added', 'Attachment added'), ('attachment_deleted', 'Attachment deleted'), ('story_points_changed', 'Story points changed'), ('estimate_changed', 'Estimate changed')], max_length=32),
        ),
    ]
