# Generated by Django 6.0.5 on 2026-07-07 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_alter_issueactivity_event_type'),
        ('label', '0002_rename_label_label_project_4a8f2d_idx_label_label_project_c81674_idx'),
        ('projects', '0006_project_default_private_visibility'),
        ('sprints', '0004_sprintsnapshot_sprintissuecommitment'),
        ('workflow', '0005_alter_issuestatushistory_transitioned_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', 'completed_at'], name='issues_project_completed_idx'),
        ),
    ]
