export const ROUTES = {
  login: '/login',
  signup: '/signup',
  board: '/board',
  dashboard: '/',
  workspaceEmpty: '/workspace/empty',
  myTasks: '/tasks',
  projectSettings: '/projects/settings',
  projectSettingsLabels: '/projects/settings/labels',
  issueDetail: '/board/issue',
  issueDetailEnhanced: '/board/issue/enhanced',
  notifications: '/notifications',
  search: '/search',
  workspaceSettings: '/workspace/settings',
  operations: '/operations',
  advancedBoard: '/board/advanced',
  qa: '/qa',
  releases: '/releases',
} as const
