# Generated by Django 5.2.11 on 2026-07-07 09:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_issue_completed_at_storypointhistory'),
        ('workflow', '0003_migrate_legacy_status_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('transitioned_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('from_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transitions_from', to='workflow.workflowstatus')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_histories', to='issues.issue')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions_to', to='workflow.workflowstatus')),
                ('transitioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_transitions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'issue status history',
                'verbose_name_plural': 'issue status histories',
                'ordering': ['-transitioned_at'],
                'indexes': [models.Index(fields=['issue', 'transitioned_at'], name='workflow_is_issue_i_430a9c_idx')],
            },
        ),
    ]
