# Generated by Django 5.2.11 on 2026-07-07 09:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_issuestatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuestatushistory',
            name='transitioned_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
