# Generated by Django 6.0.5 on 2026-07-07 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0012_analytics_constraints_indexes'),
        ('workflow', '0005_alter_issuestatushistory_transitioned_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='issuestatushistory',
            index=models.Index(condition=models.Q(('duration_seconds__isnull', True)), fields=['issue', 'to_status'], name='workflow_ish_open_records_idx'),
        ),
    ]
