from django.urls import path

from apps.issues.api.views import (
    AttachmentDetailView,
    CommentDetailView,
    IssueActivityListView,
    IssueAssignSprintView,
    IssueAttachmentListCreateView,
    IssueBulkAssignSprintView,
    IssueCommentListCreateView,
    IssueDetailView,
    IssueListCreateView,
    IssueSubtaskListCreateView,
    IssueTransitionView,
    ProjectBacklogIssuesView,
    ProjectBacklogMetadataView,
    ProjectBacklogSprintIssuesView,
    ProjectBoardColumnView,
    ProjectKanbanFiltersView,
    ProjectKanbanView,
    SprintKanbanView,
    SubtaskDetailView,
)

urlpatterns = [
    path("issues", IssueListCreateView.as_view(), name="issue-list-create"),
    path(
        "projects/<uuid:project_id>/kanban",
        ProjectKanbanView.as_view(),
        name="project-kanban",
    ),
    path(
        "projects/<uuid:project_id>/board",
        ProjectKanbanView.as_view(),
        name="project-board",
    ),
    path(
        "projects/<uuid:project_id>/board/columns/<str:column_id>",
        ProjectBoardColumnView.as_view(),
        name="project-board-column",
    ),
    path(
        "projects/<uuid:project_id>/kanban/columns/<str:column_id>",
        ProjectBoardColumnView.as_view(),
        name="project-kanban-column",
    ),
    path(
        "projects/<uuid:project_id>/kanban/filters",
        ProjectKanbanFiltersView.as_view(),
        name="project-kanban-filters",
    ),
    path(
        "projects/<uuid:project_id>/backlog",
        ProjectBacklogMetadataView.as_view(),
        name="project-backlog-metadata",
    ),
    path(
        "projects/<uuid:project_id>/backlog/issues",
        ProjectBacklogIssuesView.as_view(),
        name="project-backlog-issues",
    ),
    path(
        "projects/<uuid:project_id>/backlog/sprints/<uuid:sprint_id>/issues",
        ProjectBacklogSprintIssuesView.as_view(),
        name="project-backlog-sprint-issues",
    ),
    path(
        "sprints/<uuid:sprint_id>/board",
        SprintKanbanView.as_view(),
        name="sprint-kanban",
    ),
    path(
        "issues/bulk/assign-sprint",
        IssueBulkAssignSprintView.as_view(),
        name="issue-bulk-assign-sprint",
    ),
    path("issues/<uuid:issue_id>", IssueDetailView.as_view(), name="issue-detail"),
    path(
        "issues/<uuid:issue_id>/transition",
        IssueTransitionView.as_view(),
        name="issue-transition",
    ),
    path(
        "issues/<uuid:issue_id>/assign-sprint",
        IssueAssignSprintView.as_view(),
        name="issue-assign-sprint",
    ),
    path(
        "issues/<uuid:issue_id>/comments",
        IssueCommentListCreateView.as_view(),
        name="issue-comment-list-create",
    ),
    path(
        "issues/<uuid:issue_id>/activity",
        IssueActivityListView.as_view(),
        name="issue-activity-list",
    ),
    path(
        "issues/<uuid:issue_id>/attachments",
        IssueAttachmentListCreateView.as_view(),
        name="issue-attachment-list-create",
    ),
    path(
        "issues/<uuid:issue_id>/subtasks",
        IssueSubtaskListCreateView.as_view(),
        name="issue-subtask-list-create",
    ),
    path(
        "subtasks/<uuid:subtask_id>",
        SubtaskDetailView.as_view(),
        name="subtask-detail",
    ),
    path(
        "comments/<uuid:comment_id>",
        CommentDetailView.as_view(),
        name="comment-detail",
    ),
    path(
        "attachments/<uuid:attachment_id>",
        AttachmentDetailView.as_view(),
        name="attachment-detail",
    ),
]
