"""
Permission module contract — authorization interface surface.

All authorization flows through PermissionService (Phase 3).
Views and services must never perform inline role checks.
"""
from typing import Protocol
from uuid import UUID


class PermissionServiceProtocol(Protocol):
    def can_view_organization(self, user_id: UUID, organization_id: UUID) -> bool: ...
    def can_manage_organization(self, user_id: UUID, organization_id: UUID) -> bool: ...
    def can_create_project(self, user_id: UUID, organization_id: UUID) -> bool: ...
    def can_view_project(self, user_id: UUID, project_id: UUID) -> bool: ...
    def can_edit_project(self, user_id: UUID, project_id: UUID) -> bool: ...
    def can_manage_members(self, user_id: UUID, project_id: UUID) -> bool: ...
    def can_manage_labels(self, user_id: UUID, project_id: UUID) -> bool: ...
    def can_manage_workflow(self, user_id: UUID, project_id: UUID) -> bool: ...
    def can_edit_issue(self, user_id: UUID, issue_id: UUID) -> bool: ...
    def can_assign_issue(self, user_id: UUID, issue_id: UUID) -> bool: ...
    def can_transition_issue(self, user_id: UUID, project_id: UUID) -> bool: ...
    def can_manage_sprint(self, user_id: UUID, project_id: UUID) -> bool: ...
    def can_plan_sprint(self, user_id: UUID, project_id: UUID) -> bool: ...
    def can_view_issue(self, user_id: UUID, project_id: UUID) -> bool: ...
    def can_view_sprint(self, user_id: UUID, project_id: UUID) -> bool: ...
    def can_start_sprint(self, user_id: UUID, project_id: UUID) -> bool: ...
    def can_complete_sprint(self, user_id: UUID, project_id: UUID) -> bool: ...
